FROM node:20-alpine
# base image selected form the hub it is the node rumtime with an alpine version it is a light weight version of linux
WORKDIR /app
# /app is standard convention 
# curr dir current dir with in the container
COPY . .

#  specify the command to run the app

CMD node hello.js